# 12. 모든 것은 항상 실패한다: 예외필터

<aside>
💡 모든 것은 항상 실패한다.

- 베르너 보겔스 (Werner Vgels, AWS CTO ) - 

</aside>

소프트웨어를 개발하면서 예외(exception) 처리는 필수 사항이다. 

어떤 상황에서든 에러는 발생할 수 있고 개발자는 이 에러에 대응책을 마련해둬야 한다. 

AWS의 CTO 베르너 보겔스는 “모든 것은 항상 실패한다” 라는 말로 장애 대응의 중요성에 대해 역설했다. 

물론 AWS 서비스의 고가용성을 강조하기 위한 말이었겠지만 새겨들을만 하다. 

장애 또는 예외가 발생했을 때 어디에 예외 처리 코드를 넣어야 할까. 

예외가 발생할만한 모든 곳에 예외 처리 코드를 삽입하는 것은 중복 코드를 양산할 뿐 아니라 기능 구현과 관련 없는 코드가 삽입되므로 핵심 기능 구현에 집중하지 못하게 된다. 

예외가 발생했을 때 에러 로그와 콜 스택을 남겨 디버깅에 사용할 수 있는 별도의 모듈을 작성했다면 , 에러 처리기 역시 따로 만들어 한곳에서 공통으로 처리하도록 해야 한다. 

## 12.1 예외 처리

Nest는 프레임워크 내에 예외 레이어를 두고 있다. 

애플리케이션을 통틀어 제대로 처리하지 못한 예외를 처리하는 역할을 한다. 

아무런 작업을 하지 않아도 기본 예외 처리기가 예외를 잡아서 유저가 이해하기 쉬운 형태로 변환하여 전송한다. 

간단하게 예외를 일으켜서 에러가 어떻게 발생하는지 확인.

```tsx
//app.controller.ts
import { Controller, Get, InternalServerErrorException } from '@nestjs/common';
...

@Controller()
export class AppController {
  ...
  @Get('/error')
  error(foo: any): string {
    return foo.bar();
  }
}
```

foo가 undefined이기 때문에 다음과 같은 에러가 발생한다. 

```tsx
curl http://localhost:3000/error

{
	"statusCode":500,
	"message":"Internal Server Error"
}
```

Nest는 예외에 대한 많은 클래스를 제공한다. 

위 결과를 보면 에러가 발생했을 때 응답을 JSON 형식으로 바꿔주고 있는데 이는 기본으로 내장된 전역 예외 필터가 처리한다.

내장 예외 필터는 인식할 수 없는 에러(HttpException도 아니고, HttpException을 상속받지도 않은 에러)를 InternalServerErrorException으로 반환한다.

[MDN문서](https://developer.mozilla.org/ko/docs/Web/HTTP/Status/500)에 따르면 500 InternalServerError는 “요청을 처리하는 과정에서 서버가 예상하지 못한 상황에 놓였다는 것을 나타낸다”고 되어있다.

InternalServerErrorException의 선언을 보면 HttpException을 상속받고 있고, HttpException은 다시 자바스크립트의 Error를 상속한다.

결국 모든 예외는 Error 객체로부터 파생된 것이다.

```tsx
export declare class InternalServerErrorException extends HttpException {
    constructor(objectOrError?: string | object | any, description?: string);
}

export declare class HttpException extends Error {
	...
}
```

그 외 Nest에서 제공하는 모든 예외 역시 HttpException을 상속하고 있다. 

이 예외 클래스를 이용하여 상황에 따라 적절한 예외를 던지면 된다. (throw)

적절한 예외 처리는 API를 호출한 클라이언트에서 에러를 쉽게 이해하고 대처할 수 있도록 한다.

예를 들어 유저 정보를 가져오기 위해 /useers/:id 엔드포인트로 조회를 하려고 하는데, 책에서는 도메인 규칙상 id가 1보다 작을 수 없다고 정했다 (3.1.4절 참고)

따라서 클라이언트가 id를 0과 같이 잘못된 값으로 전달하는 경우는 [400 Bad Request](https://developer.mozilla.org/ko/docs/Web/HTTP/Status/400)를 응답으로 보낸다.

```tsx
//users.controller.ts
@Get(':id')
  findOne(@Param('id') id: string) {
    if (+id < 1) {
			// 1. 단순 문자열
      throw new BadRequestException('id는 0보다 큰 정수여야 합니다');
		}
    return this.usersService.findOne(+id);
  }
```

```bash
$ curl http://localhost:3000/users/0 -v 

*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /users/0 HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/8.1.2
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< X-Powered-By: Express
< Content-Type: application/json; charset=utf-8
< Content-Length: 93
< ETag: W/"5d-IQgU1nITlBdrWSxZCLVbQse97I8"
< Date: Tue, 31 Oct 2023 04:49:20 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host localhost left intact
{
	"statusCode":400,
	"message":"id는 0보다 큰 정수여야 합니다",
	"error":"Bad Request"
}
```

예외의 생성자에 전달할 메시지가 응답에 함께 출력되었다.

HttpException 클래스를 다시 자세히 살펴보자.

```tsx
export declare class HttpException extends Error {
		...
    constructor(response: string | Record<string, any>, status: number);
    ...
}
```

생성자는 2개의 인수를 받는다. 

- response: JSON응답의 본문이다. 문자열이나 Record<string, any> 타입의 객체를 전달할 수 있다.
- status: 에러의 속성을 나타내는 HTTP 상태 코드이다.

JSON응답의 본문은 statusCode와 message 속성을 기본으로 가진다. 

이 값은 위에서 예를 만들 때 생성자에 넣어준 response와 status로 구성한다. 

미리 제공된 BadRequestException 대신 HttpException을 직접 전달하려면 다음과 같이 작성한다. 

```tsx
@Get(':id')
  findOne(@Param('id') id: string) {
    if (+id < 1) {
      // 2. HttpException
      throw new HttpException(
        {
          errorMessage: 'id는 0보다 큰 정수여야 합니다',
          foo: 'bar'
        },
        HttpStatus.BAD_REQUEST
      );
		}
	}
    return this.usersService.findOne(+id);
}
```

```bash
curl http://localhost:3000/users/0 -v

*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /users/0 HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/8.1.2
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< X-Powered-By: Express
< Content-Type: application/json; charset=utf-8
< Content-Length: 71
< ETag: W/"47-H1uUgE8tcmr3NfMhBPY9JTe6N8A"
< Date: Tue, 31 Oct 2023 04:59:51 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host localhost left intact
{
	"errorMessage":"id는 0보다 큰 정수여야 합니다",
	"foo":"bar"
}
```

- **Nest에서 제공하는 표준 예외들** 
(자주 쓰지 않는 것들도 있지만, 어떤 상황에서 어떤 에러를 내야 하는지 MDN문서 읽어볼것)
    
    
    - BadRequestException
    - UnauthorizedException
    - NotFoundException
    - ForbiddenException
    - NotAcceptableException
    - RequestTimeoutException
    - ConflictException
    - GoneException
    - HttpVersionNotSupportedException
    - PayloadTooLargeException
    
    - UnsupportedMediaTypeException
    - UnprocessableEntityException
    - InternalServerErrorException
    - NotImplementedException
    - ImATeapotException
    - MethodNotAllowedException
    - BadGatewayException
    - ServiceUnavailableException
    - GatewayTimeoutException
    - PreconditionFailedException

Nest에서 제공하는 기본 예외 클래스는 모두 생성자가 다음과 같은 모양을 가진다. 

`constructor(objectOrError?: string | object | any, description?: string);`

[BadRequestException의 내부 구현](https://github.com/nestjs/nest/blob/master/packages/common/exceptions/bad-request.exception.ts)을 보면 전달받은 objectOrError와 description으로 HttpException생성자의 첫 번째 인수(response)를 구성하는 것을 볼 수 있다. 

그럴 경우는 거의 없겠지만 만약 필요에 의해 HttpException을 상속받은 예외 클래스를 직접 만든다고 하면 이를 참조하면 된다. 

```bash
export class BadRequestException extends HttpException {
	constructor(
    objectOrError?: string | object | any,
    descriptionOrOptions: string | HttpExceptionOptions = 'Bad Request',
  ) {
    const { description, httpExceptionOptions } =
      HttpException.extractDescriptionAndOptionsFrom(descriptionOrOptions);

    super(
      HttpException.createBody(
        objectOrError,
        description,
        HttpStatus.BAD_REQUEST,
      ),
      HttpStatus.BAD_REQUEST,
      httpExceptionOptions,
    );
  }
}
```

BadRequestException을 던진 예외를 조금 바꿔 description을 전달해보자

```tsx
@Get(':id')
  findOne(@Param('id') id: string) {
    if (+id < 1) {
      // 3. 기본 제공 예외에 description을 함께 전달
      throw new BadRequestException('id는 0보다 큰 정수여야 합니다', 'id format exception');
    }

    return this.usersService.findOne(+id);
  }
```

```bash
$ curl http://localhost:3000/users/0 -v

*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /users/0 HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/8.1.2
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< X-Powered-By: Express
< Content-Type: application/json; charset=utf-8
< Content-Length: 101
< ETag: W/"65-1TAwbLoaawl8inRfDn/rxDlThXM"
< Date: Tue, 31 Oct 2023 05:20:57 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host localhost left intact
{
	"statusCode":400,
	"message":"id는 0보다 큰 정수여야 합니다",
	"error":"id format exception"
}
```

## 12.2 예외 필터

![Pipe_1.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/380da689-6e0b-4496-b9c4-07070d4b592a/1f09721f-e013-418e-ad94-a63604261f82/Pipe_1.png)

Nest에서 제공하는 전역 예외 필터 외에 직접 **예외 필터**(exception filter) 

예외가 일어났을 때 로그를 남기거나 응답 객체를 원하는 대로 변경하고자 하는 등의 요사항을 해결하고자 할 때 사용한다. 

예외가 발생했을 때 모든 예외(Error)를 잡아서 요청 URL과 예외가 발생한 시각을 콘솔에 출력하는 예외 필터를 만들어보자.

```tsx
//http-exception.filter.ts
import { ArgumentsHost, Catch, ExceptionFilter, HttpException, InternalServerErrorException } from '@nestjs/common';
import { Request, Response } from 'express';

@Catch()  //1
export class HttpExceptionFilter implements ExceptionFilter {
  catch(exception: Error, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const res = ctx.getResponse<Response>();
    const req = ctx.getRequest<Request>();

    if (!(exception instanceof HttpException)) {  //2
      exception = new InternalServerErrorException();
    }

    const response = (exception as HttpException).getResponse();

    const log = {
      timestamp: new Date(),
      url: req.url,
      response,
    }

    console.log(log);

    res
      .status((exception as HttpException).getStatus())
      .json(response);
  }
}
```

> 1) @Catch 데커레이터는 처리되지 않은 모든 예외를 잡으려고 할 때 사용한다.
> 
> 
> 2) 우리가 다루는 대부분의 예외는 이미 Nest에서 HttpException을 상속받는 클래스들로 제공한다.  HttpException이 아닌 예외는 알 수 없는 에러이므로 InternalServerErrorException으로 처리되도록 했다. 
> 

만든 HttpExceptionFilter를 적용해보자. 

예외 필터는 @UserFilter 데커레이터로 컨트롤러에 직접 적용하거나 전역으로 적용할 수 있다. 

예외 필터는 전역 필터를 하나만 가지도록 하는 것이 일반적이다.

- 특정 엔드포인트에 적용할 때

```tsx
...
@Controller('users')
export class UsersController {
  constructor(private readonly usersService: UsersService) { }

  @UseFilters(HttpExceptionFilter)
  @Post()
  create(@Body() createUserDto: CreateUserDto) {
    return this.usersService.create(createUserDto);
  }
	...
}
```

- 특정 컨트롤러 전체에 적용할 때

```tsx
...
@Controller('users')
@UseFilters(HttpExceptionFilter)
export class UsersController {
	...
}
```

- 애플리케이션 전체에 적용할 때

```tsx
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { HttpExceptionFilter } from './http-exception.filter';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useGlobalFilters(new HttpExceptionFilter());  // 전역 필터 적용
  await app.listen(3000);
}
bootstrap();
```

부트스트랩 과정에서 전역 필터를 적용하는 방식은 필터에 의존성을 주입할 수 없다는 제약이 있다.

예외 필터의 수행이 예외가 발생한 모듈 외부(main.ts)에서 이뤄지기 대문이다.

의존성 주입을 받고자 한다면 예외 필터를 커스텀 프로바이더로 등록하면 된다.

```tsx
import { Logger, Module } from '@nestjs/common';
import { APP_FILTER } from '@nestjs/core';
...

@Module({
  ...
  providers: [
    ...
    {
      provide: APP_FILTER, 
      useClass: HttpExceptionFilter 
    },
  ],
})
export class AppModule { }
```

이제 HttpExceptionFilter는 다른 프로바이더를 주입받아 사용할 수 있다. 

예를 들어 외부 모듈에서 제공하는 Logger객체를 사용한다고 하면 다음과 같이 구현 가능하다.

```tsx
export class HttpExceptionFilter implements ExceptionFilter {
	constructor(private logger: Logger) {}
	...
}
```

이제 다시 에러를 일으켜보고 콘솔에 출력되는 로그를 확인해보자

```bash
$ curl http://localhost:3000/error

{
  timestamp: 2023-10-31T05:55:18.422Z,
  url: '/error',
  response: { statusCode: 500, message: 'Internal Server Error' }
}
```

```bash
$ curl http://localhost:3000/users/0

{
  timestamp: 2023-10-31T06:07:51.280Z,
  url: '/users/0',
  response: {
    statusCode: 400,
    message: 'id는 0보다 큰 정수여야 합니다',
    error: 'id format exception'
  }
}
```

이렇게 예외 필터는 try/catch로 잡지 못한 예외가 발생했을 때 실행된다. 

잡지 못한 에외가 발생하면 나머지 생명주기를 무시하고 예외 필터로 건너 뛰게 된다. 

## 12.3 유저 서비스에 예외 필터 적용하기

유저 서비스에 예외 필터를 적용하는 것은 앞에서 배운 내용에서 딱히 크게 추가할 부분이 없다.

이전에 만든 HttpExceptionFilter와 아ㅠ 장에서 만든 LoggerService를 사용한다.

HttpExceptionFilter는 Logger를 주입받아 사용하는 방식으로 적용해보자.

[12.3 유저 서비스에 예외 필터 적용하기](https://www.notion.so/12-3-cb64aa3335e2490b80f08ee85dad721f?pvs=21)